# Generated by Django 4.1.6 on 2023-03-03 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency', '0003_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('source_url', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
    ]
